-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 05:06:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bourdillat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bourdillat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bourdillat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `bourdillat` ;

-- -----------------------------------------------------
-- Table `bourdillat`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`collection` (
  `collection_id` INT NOT NULL AUTO_INCREMENT,
  `collection_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`collection_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(8) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `fname` VARCHAR(12) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `documents` INT NOT NULL,
  PRIMARY KEY (`user_id`, `documents`),
  INDEX `fk_user_collection1_idx` (`documents` ASC),
  CONSTRAINT `fk_user_collection1`
    FOREIGN KEY (`documents`)
    REFERENCES `bourdillat`.`collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`document` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `document_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`document_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`user_has_collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`user_has_collection` (
  `user_id` INT NOT NULL,
  `collection_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `collection_id`),
  INDEX `fk_user_has_collection_collection1_idx` (`collection_id` ASC),
  INDEX `fk_user_has_collection_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_collection_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bourdillat`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_collection_collection1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `bourdillat`.`collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`collection_has_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`collection_has_document` (
  `collection_id` INT NOT NULL,
  `document_id` INT NOT NULL,
  PRIMARY KEY (`collection_id`, `document_id`),
  INDEX `fk_collection_has_document_document1_idx` (`document_id` ASC),
  INDEX `fk_collection_has_document_collection1_idx` (`collection_id` ASC),
  CONSTRAINT `fk_collection_has_document_collection1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `bourdillat`.`collection` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collection_has_document_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `bourdillat`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`lemma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`lemma` (
  `lemma_id` INT NOT NULL AUTO_INCREMENT,
  `lemma_form` VARCHAR(20) NOT NULL,
  `pos` ENUM('ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X') NOT NULL,
  PRIMARY KEY (`lemma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`sentence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`sentence` (
  `sentence_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('DEC', 'INT', 'EXC') NOT NULL,
  `text_id` INT NOT NULL,
  PRIMARY KEY (`sentence_id`, `text_id`),
  INDEX `fk_sentence_document1_idx` (`text_id` ASC),
  CONSTRAINT `fk_sentence_document1`
    FOREIGN KEY (`text_id`)
    REFERENCES `bourdillat`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bourdillat`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bourdillat`.`token` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `token_sent_id` INT NULL,
  `token_form` VARCHAR(20) NOT NULL,
  `lemma` INT NOT NULL,
  `sentence` INT NOT NULL,
  `deprel` ENUM('acl', 'acl:relcl', 'advcl', 'advmod', 'advmod:emph', 'advmod:lmod', 'amod', 'appos', 'aux', 'aux:pass', 'case', 'cc', 'cc:preconj', 'ccomp', 'clf', 'compound', 'compound:lvc', 'compound:prt', 'compound:redup', 'compound:svc', 'conj', 'cop', 'csubj', 'csubj:outer', 'csubj:pass', 'dep', 'det', 'det:numgov', 'det:nummod', 'det:poss', 'discourse', 'dislocated', 'expl', 'expl:impers', 'expl:pass', 'expl:pv', 'fixed', 'flat', 'flat:foreign', 'flat:name', 'goeswith', 'iobj', 'list', 'mark', 'nmod', 'nmod:poss', 'nmod:tmod', 'nsubj', 'nsubj:outer', 'nsubj:pass', 'nummod', 'nummod:gov', 'obj', 'obl', 'obl:agent', 'obl:arg', 'obl:lmod', 'obl:tmod', 'orphan', 'parataxis', 'punct', 'reparandum', 'root', 'vocative', 'xcomp') NULL,
  `head` INT NULL,
  PRIMARY KEY (`token_id`, `lemma`, `sentence`),
  INDEX `fk_token_lemma1_idx` (`lemma` ASC),
  INDEX `fk_token_sentence1_idx` (`sentence` ASC),
  INDEX `fk_token_token1_idx` (`head` ASC),
  CONSTRAINT `fk_token_lemma1`
    FOREIGN KEY (`lemma`)
    REFERENCES `bourdillat`.`lemma` (`lemma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_token_sentence1`
    FOREIGN KEY (`sentence`)
    REFERENCES `bourdillat`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_token_token1`
    FOREIGN KEY (`head`)
    REFERENCES `bourdillat`.`token` (`token_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
